In [2]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris
import pandas as pd

In [3]:
iris = load_iris()

In [4]:
model_params = {
    "SVC": {
        "model": SVC(gamma = "auto"),
        "params":{
            "C":[1, 10, 20],
            "kernel":["rbf", "linear"]
        }
    },
    "random_forest":{
        "model":RandomForestClassifier(),
        "params":{
            "n_estimators":[1, 5, 10]
        }
    },
    "logistic_regression":{
        "model":LogisticRegression(solver = "liblinear", multi_class = "auto"),
        "params":{
            "C":[1, 5, 10]
        }
    }
}

In [5]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp["model"], mp["params"], cv = 5, return_train_score = False)
    clf.fit(iris.data, iris.target)
    scores.append({"model": model_name, "best_score":clf.best_score_, "best_params":clf.best_params_})

In [6]:
df = pd.DataFrame(scores, columns = ["model", "best_score", "best_params"])
df

                 model  best_score                best_params
0                  SVC    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.966667        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}

In [8]:
pd.DataFrame(clf.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003792,0.005723,0.000203,0.000406,1,{'C': 1},1.0,0.966667,0.933333,0.9,1.0,0.960000,0.038873,3
1,0.000000,0.000000,0.000000,0.000000,5,{'C': 5},1.0,1.000000,0.933333,0.9,1.0,0.966667,0.042164,1
2,0.002165,0.003004,0.000258,0.000515,10,{'C': 10},1.0,1.000000,0.933333,0.9,1.0,0.966667,0.042164,1